# Basic Jekyll configuration
title: "Neurodivergent Survival Guide"
description: "Navigate daily friction points with understanding and practical tools"
url: "https://neurodivergentsurvival.guide"
baseurl: ""  # Empty for custom domains

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages specific
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-default-layout

# Exclude from processing
exclude:
  - README.md
  - "Neurodivergent Survival Guide: Complete Project Specification.md"
  - "Handoff Doc.md"
  - "Toolkit Design Guide & Content Outlines.md"

# Sass
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: "conditions"
      type: "pages"
    values:
      layout: "condition"
