# Basic Jekyll configuration
title: "Neurodivergent Survival Guide"
description: "Navigate daily friction points with understanding and practical tools"
url: "https://neurodivergent-survival-guide.github.io"
baseurl: "/neurodivergent-survival-guide"

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages specific
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - "Neurodivergent Survival Guide: Complete Project Specification.md"
  - "Handoff Doc.md"

# Sass
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
